# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_demo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="grpc_demo.proto",
    package="seismo",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\x0fgrpc_demo.proto\x12\x06seismo"!\n\x11SeismoPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t""\n\x0fSeismoPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t2S\n\rSeismoService\x12\x42\n\nSeismoPing\x12\x19.seismo.SeismoPingRequest\x1a\x17.seismo.SeismoPingReply"\x00\x62\x06proto3',
)


_SEISMOPINGREQUEST = _descriptor.Descriptor(
    name="SeismoPingRequest",
    full_name="seismo.SeismoPingRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="seismo.SeismoPingRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=27,
    serialized_end=60,
)


_SEISMOPINGREPLY = _descriptor.Descriptor(
    name="SeismoPingReply",
    full_name="seismo.SeismoPingReply",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="seismo.SeismoPingReply.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=62,
    serialized_end=96,
)

DESCRIPTOR.message_types_by_name["SeismoPingRequest"] = _SEISMOPINGREQUEST
DESCRIPTOR.message_types_by_name["SeismoPingReply"] = _SEISMOPINGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SeismoPingRequest = _reflection.GeneratedProtocolMessageType(
    "SeismoPingRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEISMOPINGREQUEST,
        "__module__": "grpc_demo_pb2"
        # @@protoc_insertion_point(class_scope:seismo.SeismoPingRequest)
    },
)
_sym_db.RegisterMessage(SeismoPingRequest)

SeismoPingReply = _reflection.GeneratedProtocolMessageType(
    "SeismoPingReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _SEISMOPINGREPLY,
        "__module__": "grpc_demo_pb2"
        # @@protoc_insertion_point(class_scope:seismo.SeismoPingReply)
    },
)
_sym_db.RegisterMessage(SeismoPingReply)


_SEISMOSERVICE = _descriptor.ServiceDescriptor(
    name="SeismoService",
    full_name="seismo.SeismoService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=98,
    serialized_end=181,
    methods=[
        _descriptor.MethodDescriptor(
            name="SeismoPing",
            full_name="seismo.SeismoService.SeismoPing",
            index=0,
            containing_service=None,
            input_type=_SEISMOPINGREQUEST,
            output_type=_SEISMOPINGREPLY,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_SEISMOSERVICE)

DESCRIPTOR.services_by_name["SeismoService"] = _SEISMOSERVICE

# @@protoc_insertion_point(module_scope)
